# Generated by Django 6.0.6 on 2026-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_channel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='disable_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='recovery_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
