# Generated by Django 6.0.2 on 2026-06-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_channel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='last_notified_status',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
